language: node_js
node_js:
- '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - node_modules
sudo: required
script: "npm test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"